version: '2'

services:
  ca:
    image: acushon/prod-ca 
    ports:
      - 5000:80
    networks:
      - pki
    volumes:
      - /home/al/data:/app/data
  
  pub:
    image: acushon/prod-pub 
    ports:
      - 5001:80
    networks:
      - pki
    volumes:
      - /home/al/data:/app/data

  pri:
    image: acushon/prod-pri 
    ports:
      - 5002:80
    networks:
      - pki
    volumes:
      - /home/al/data:/app/data
  
  sig:
    image: acushon/prod-sig 
    ports:
      - 5003:80
    networks:
      - pki
    volumes:
      - /home/data:/app/data

networks:
  pki:
